spring:
  aop:
    auto: true
  dubbo:
    server: true
    application:
      name: web-deploy
    consumer:
      timeout: 10000
      retries: 3
      # 启动检查，避免依赖服务未启动导致Spring启动报差错
      check: false
    registry:
      # 注册地址，配置多个会报错
      address: zookeeper://106.14.156.120:2181
    protocol:
      name: dubbo
      port: 20882

server:
  servlet:
    context-path: /blog-web
  port: 8088

littlefisher:
  shiro:
    enabled: false
    login-url: /login
    success-url: /success
    unauthorized-url: /index
    swagger-file-chain-enable: true
    filter-chain-definition:
      # authc:所有url都必须认证通过才可以访问; anon:所有url都都可以匿名访问
      /static/*: anon
      /*: authc