spring:
  aop:
    auto: true
  application:
    name: web

server:
  servlet:
    context-path: /blog-web
  port: 8088

littlefisher:
  shiro:
    enabled: false
    login-url: /login
    success-url: /success
    unauthorized-url: /index
    swagger-file-chain-enable: true
    filter-chain-definition:
      # authc:所有url都必须认证通过才可以访问; anon:所有url都都可以匿名访问
      /static/*: anon
      /*: authc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka